import {samples,scenes,categories,initialState,loadState,exactDuplicate,similarDuplicate,addItem,matchItem,recommendation,saveFavorite,deleteItem,validateUpload} from './domain.mjs';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal'),KEY='yida-demo-v1';
let state;try{state=loadState(localStorage.getItem(KEY))}catch{state=initialState()}
let view='home',filter='全部',picker=false,active=null,scene=scenes[0],variant=0,result=null,busy=false,request=0,toastTimer,returnFocus=null;
const icons={plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v13H4z"/><circle cx="12" cy="13" r="4"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',heart:'<path d="M20 5c-3-3-6-1-8 1-2-2-5-4-8-1s0 7 8 14c8-7 11-11 8-14z"/>',spark:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4z"/>',refresh:'<path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/>',closet:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M12 3v18M9 11v3m6-3v3"/>',trash:'<path d="M4 6h16M9 3h6M6 6l1 15h10l1-15M10 10v7m4-7v7"/>'};
const icon=n=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(icons[n]||icons.plus)+'</svg>';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(item,cls='')=>'<img class="'+cls+'" src="'+esc(item.image)+'" alt="'+esc(item.name)+'" loading="lazy">';
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;return true}catch{toast('浏览器保存失败：空间不足或存储被禁用。当前操作未保存。');return false}}
function go(v){request++;busy=false;view=v;picker=false;render();window.scrollTo({top:0,behavior:'smooth'})}
function header(){document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===view||(view==='result'&&b.dataset.view==='home'));b.setAttribute('aria-current',b.classList.contains('active')?'page':'false')});$('#nav-count').textContent=String(state.wardrobe.length).padStart(2,'0')}
function button(text,action,cls='secondary',ico=''){return '<button class="'+cls+'" data-action="'+action+'">'+(ico?icon(ico):'')+text+'</button>'}
function home(){return '<div class="title-row"><div><p class="eyebrow">YOUR EVERYDAY STYLING STUDIO</p><h1>今天，从这件开始。</h1></div><p class="sub">不用录入整个衣柜。<br>一件上衣，就能找到新的搭配可能。</p></div><section class="workbench"><div class="intro-art"><img src="assets/tee.jpg" alt="白色圆领 T 恤示例" class="hero-photo"><div class="photo-label"><span>THE EVERYDAY ESSENTIAL</span><span>01 / 04</span></div><div class="art-caption"><div><small>今日灵感 / EVERYDAY</small><strong>一件白 T，无限可能。</strong></div><button class="round-icon" data-action="example" aria-label="体验白色 T 恤搭配">'+icon('arrow')+'</button></div></div><div class="upload-pane"><div class="step-label">01 / 选择搭配起点</div><h2>想穿哪件上衣？</h2><p class="sub">拍下来，发现裤子与鞋子的搭配灵感。</p><div class="dropzone" id="dropzone"><div class="upload-icon">'+icon('upload')+'</div><p>把衣物照片拖到这里</p><small>JPG、PNG、WebP · 最大 10 MB</small></div><div class="button-row">'+button('拍照 / 上传','upload','primary','camera')+button('从衣柜选','choose','secondary','closet')+'</div><div class="divider">也可以先试一试</div><button class="sample-link" data-action="example"><span>用这件白 T，体验一次搭配</span>'+icon('arrow')+'</button><p class="privacy">照片仅在浏览器处理。确认后自动收录衣柜。<br>DEMO · 识别、推荐与 AI 图片均以预设数据模拟。</p></div></section><div class="section-head"><h2>衣柜里，已有的可能 <small>拍过的衣服，下次直接用</small></h2><button class="text-btn" data-view="wardrobe">查看衣柜 '+icon('arrow')+'</button></div><div class="wardrobe-strip">'+state.wardrobe.slice(0,3).map(i=>'<button class="mini-item" data-item="'+i.id+'">'+img(i,'thumb')+'<span><strong>'+esc(i.name)+'</strong><small>'+esc(i.category)+' · '+(i.sample?'示例衣物':'已收录')+'</small></span>'+icon('arrow')+'</button>').join('')+'<button class="mini-item add-mini" data-action="add">'+icon('plus')+'<span><strong>再认识一件衣服</strong><small>衣柜，慢慢建立就好</small></span></button></div><div class="flow-note"><span><b>01</b> 拍照选衣</span>／<span><b>02</b> 确认并收录</span>／<span><b>03</b> 获取搭配灵感</span></div>'}
function wardrobe(){const items=state.wardrobe.filter(i=>(filter==='全部'||i.category===filter));return '<div class="title-row"><div><p class="eyebrow">YOUR PERSONAL COLLECTION</p><h1>'+(picker?'选一件上衣，开始搭配。':'我的衣柜。')+'</h1><p class="sub">'+(picker?'点选已收录的上衣，不需要重新拍照。':'边穿边记录，让熟悉的衣服有新的组合。')+'</p></div>'+button('收录一件','add','primary','plus')+'</div><div class="collection-bar"><div class="chips" role="group" aria-label="衣柜类别">'+['全部',...categories].map(c=>'<button class="chip '+(filter===c?'selected':'')+'" data-filter="'+c+'">'+c+' <span>'+state.wardrobe.filter(i=>c==='全部'||i.category===c).length+'</span></button>').join('')+'</div><span class="small-muted">共 '+state.wardrobe.length+' 件 · 本机保存</span></div>'+(items.length?'<div class="closet-grid">'+items.map(i=>'<article class="garment-card"><button class="garment-image" data-item="'+i.id+'" aria-label="查看'+esc(i.name)+'">'+img(i)+'<span class="photo-badge">'+(i.sample?'示例衣物':'已收录')+'</span></button><div class="garment-meta"><div><h3>'+esc(i.name)+'</h3><p>'+esc(i.type)+' / '+esc(i.fit)+'</p></div><button class="round-icon" data-item="'+i.id+'" aria-label="查看衣物详情">'+icon('arrow')+'</button></div></article>').join('')+'<button class="add-card" data-action="add">'+icon('plus')+'<strong>拍一件，收录一件</strong><span>不着急，一点点建立自己的衣柜。</span></button></div>':'<div class="empty">'+icon('closet')+'<h2>这里，还在等第一件衣服。</h2><p>从一张照片开始，不需要一次录入全部。</p>'+button('拍照收录','add','primary','camera')+'</div>')+'<div class="local-note">衣柜与收藏仅保存在当前浏览器。清除浏览器数据后会丢失。<button class="text-btn" data-action="reset">重置演示数据</button></div>'}
function matchCard(target,label){const owned=matchItem(state.wardrobe,target),shown=owned||target;return '<article class="recommend-item"><div class="item-heading"><span>'+label+'</span><span class="status-badge '+(owned?'owned':'reference')+'">'+icon(owned?'check':'spark')+(owned?'衣柜已有'+(owned.sample?' · 示例':''):'AI 参考款 · 模拟')+'</span></div><div class="recommend-photo">'+img(shown)+'</div><div class="item-info"><h3>'+esc(target.name)+'</h3><p>'+esc(target.color)+' / '+esc(target.fit)+'</p>'+(owned?'<button class="text-btn" data-item="'+owned.id+'">查看衣柜里的这件 '+icon('arrow')+'</button>':'<span class="not-found">衣柜暂未找到匹配款</span><button class="text-btn" data-action="found">我找到相似的了 '+icon('plus')+'</button>')+'</div></article>'}
function results(){if(!result)return home();const saved=state.favorites.some(f=>f.id===result.id);return '<button class="text-btn back" data-view="home">'+icon('back')+'重新选一件</button><div class="title-row"><div><p class="eyebrow">A LITTLE INSPIRATION FOR YOU</p><h1>'+esc(result.title)+'</h1></div><span class="mock-tag">'+icon('spark')+'预设搭配演示 / '+(variant%2+1)+' OF 2</span></div><div class="result-layout"><aside class="base-piece"><div class="step-label">搭配起点</div><div class="base-photo">'+img(result.top)+'</div><h3>'+esc(result.top.name)+'</h3><p class="sub">'+esc(result.top.color)+' · '+esc(result.top.fit)+'</p><div class="saved-label">'+icon(state.wardrobe.some(i=>i.id===result.top.id)?'check':'spark')+(state.wardrobe.some(i=>i.id===result.top.id)?'已在衣柜，下次直接选':'当前方案快照')+'</div><label class="scene-label" for="scene">今天要去哪里？</label><select id="scene">'+scenes.map(s=>'<option '+(s===result.scene?'selected':'')+'>'+s+'</option>').join('')+'<p class="privacy">结果为预设模拟，不代表 AI 实际分析了你的照片。</p></aside><div><div class="recommend-grid">'+matchCard(result.pants,'01 / 裤子')+matchCard(result.shoes,'02 / 鞋子')+'</div><div class="stylist-note"><div class="note-icon">'+icon('spark')+'</div><div><h3>这样搭的小心思</h3><p>'+esc(result.reason)+'</p><p class="tip">'+esc(result.tip)+'</p></div></div><div class="result-actions">'+button(busy?'正在准备下一套…':'换一套看看','next','secondary','refresh')+button(saved?'已收藏这套':'收藏这套搭配','favorite',saved?'primary saved':'primary','heart')+'</div><p class="reference-note">参考款使用预设商品素材模拟生成图，仅表达搭配方向，不代表你拥有该商品。</p></div></div>'}
function favorites(){return '<div class="title-row"><div><p class="eyebrow">LOOKS WORTH KEEPING</p><h1>留住心动的搭配。</h1><p class="sub">下次不知道穿什么，就来这里找灵感。</p></div><span class="small-muted">'+state.favorites.length+' 套收藏</span></div>'+(state.favorites.length?'<div class="favorites-grid">'+state.favorites.map(f=>'<article class="look-card"><button class="look-board" data-look="'+esc(f.id)+'" aria-label="查看收藏搭配"><span class="look-top">'+img(f.top)+'</span><span class="look-bottom">'+img(f.pants)+img(f.shoes)+'</span><span class="look-scene">'+esc(f.scene)+'</span></button><div class="look-meta"><div><h3>'+esc(f.top.name)+'</h3><p>'+esc(f.pants.name)+' + '+esc(f.shoes.name)+'</p></div><button class="round-icon heart-filled" data-remove-fav="'+esc(f.id)+'" aria-label="取消收藏">'+icon('heart')+'</button></div></article>').join('')+'</div>':'<div class="empty">'+icon('heart')+'<h2>下一套喜欢的搭配，留在这里。</h2><p>先从一件上衣开始，看到喜欢的就收藏。</p>'+button('去找搭配灵感','home','primary','arrow')+'</div>')}
function render(){header();app.innerHTML=view==='home'?home():view==='wardrobe'?wardrobe():view==='favorites'?favorites():results();const drop=$('#dropzone');if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();readPhoto(e.dataTransfer.files[0],true)}}app.querySelectorAll('img').forEach(el=>el.onerror=()=>{el.alt='图片暂时不可用，请重新上传';el.classList.add('image-error')})}
function openModal(content){returnFocus=document.activeElement;modal.innerHTML=content;if(!modal.open)modal.showModal()}
function closeModal(){modal.close();if(returnFocus?.isConnected)returnFocus.focus()}
const modalHead=t=>'<div class="modal-head"><h2 id="modal-title">'+t+'</h2><button class="round-icon" data-close aria-label="关闭">'+icon('close')+'</button></div>';
function choosePhoto(forOutfit){const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.onchange=()=>readPhoto(input.files[0],forOutfit);input.click()}
async function readPhoto(file,forOutfit){try{validateUpload(file);const url=URL.createObjectURL(file),picture=new Image();try{await new Promise((resolve,reject)=>{picture.onload=resolve;picture.onerror=()=>reject(Error('图片无法打开，请换一张'));picture.src=url});const canvas=document.createElement('canvas'),scale=Math.min(1,640/Math.max(picture.width,picture.height));canvas.width=Math.round(picture.width*scale);canvas.height=Math.round(picture.height*scale);canvas.getContext('2d').drawImage(picture,0,0,canvas.width,canvas.height);editDraft({...samples[0],id:crypto.randomUUID(),name:'',image:canvas.toDataURL('image/jpeg',.72),sample:false},forOutfit)}finally{URL.revokeObjectURL(url)}}catch(e){toast(e.message)}}
function options(list,current){return [...new Set([...list,current])].filter(Boolean).map(x=>'<option '+(x===current?'selected':'')+'>'+esc(x)+'</option>').join('')}
function editDraft(draft,forOutfit=false,existing=false){openModal(modalHead(existing?'整理这件衣服':'确认一下，就收进衣柜')+'<div class="edit-preview">'+img(draft)+'<span class="status-badge reference">'+(draft.sample?'示例衣物':'模拟标签 · 请手动确认')+'</span></div><p class="modal-copy">'+(existing?'修改标签会用于之后的搭配。':'这里没有真实图片识别，请按照片修改标签。确认后自动保存在当前浏览器。')+'</p><form id="item-form"><div class="form-grid"><label>类别<select name="category">'+options(forOutfit?['上衣']:categories,draft.category)+'</select></label><label>具体类型<select name="type">'+options(['T 恤','衬衫','卫衣','针织衫','牛仔裤','休闲裤','运动鞋','皮鞋'],draft.type)+'</select></label><label>颜色<select name="color">'+options(['白色','米白色','黑色','蓝色','深蓝色','灰色','绿色','红色','其他'],draft.color)+'</select></label><label>版型<select name="fit">'+options(['宽松','常规','修身','宽直筒','锥形','低帮','高帮','不确定'],draft.fit)+'</select></label></div><label class="full-label">衣物名称（可选）<input name="name" maxlength="40" placeholder="例如：最常穿的白 T" value="'+esc(draft.name)+'"></label><button class="primary full" type="submit">'+(existing?'保存修改':forOutfit?'确认并搭配':'确认并收录')+icon('arrow')+'</button></form>');
const form=$('#item-form');form.elements.category.onchange=()=>{const c=form.elements.category.value;form.elements.type.value=c==='上衣'?'T 恤':c==='裤子'?'牛仔裤':'运动鞋';form.elements.fit.value=c==='鞋子'?'低帮':c==='裤子'?'宽直筒':'常规'};
form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form)),item={...draft,...data,name:data.name.trim()||data.color+data.type};const legal={上衣:['T 恤','衬衫','卫衣','针织衫'],裤子:['牛仔裤','休闲裤'],鞋子:['运动鞋','皮鞋']};if(!legal[item.category].includes(item.type)){toast('类别与具体类型不一致，请调整后再保存');return}if(existing){if(persist({...state,wardrobe:state.wardrobe.map(i=>i.id===item.id?item:i)})){closeModal();render();toast('衣物标签已更新')}return}const duplicate=exactDuplicate(state.wardrobe,item),similar=similarDuplicate(state.wardrobe,item);if(duplicate){closeModal();toast('这张照片已经收录，已复用衣柜里的衣物');if(forOutfit)start(duplicate);else go('wardrobe');return}if(similar){openModal(modalHead('衣柜里，好像有一件相似的')+'<p class="modal-copy">类型、颜色和版型相同，但也可能是不同衣物。请选择，不会自动合并。</p><div class="duplicate-compare"><div>'+img(similar)+'<p>衣柜已有</p></div><div>'+img(item)+'<p>这次拍摄</p></div></div><div class="button-row"><button class="secondary" id="keep-existing">使用已有</button><button class="primary" id="keep-new">是另一件，仍然收录</button></div>');$('#keep-existing').onclick=()=>{closeModal();forOutfit?start(similar):go('wardrobe')};$('#keep-new').onclick=()=>commitItem(item,forOutfit);return}commitItem(item,forOutfit)}}
function commitItem(item,forOutfit){const next=addItem(state,item);if(persist(next.state)){closeModal();toast('已收录衣柜，下次可以直接选用');if(forOutfit)start(next.item);else go('wardrobe')}}
function detail(id){const item=state.wardrobe.find(i=>i.id===id);if(!item)return;openModal(modalHead(item.name)+'<div class="detail-photo">'+img(item)+'</div><div class="detail-tags"><span>'+esc(item.category)+'</span><span>'+esc(item.color)+'</span><span>'+esc(item.fit)+'</span><span>'+(item.sample?'示例衣物':'我的衣物')+'</span></div><div class="button-row">'+(item.category==='上衣'?'<button class="primary" id="use-item">'+icon('spark')+'用这件搭配</button>':'')+'<button class="secondary" id="edit-item">编辑标签</button><button class="secondary danger" id="delete-item" aria-label="删除衣物">'+icon('trash')+'</button></div>');if($('#use-item'))$('#use-item').onclick=()=>{closeModal();start(item)};$('#edit-item').onclick=()=>editDraft(item,false,true);$('#delete-item').onclick=()=>{openModal(modalHead('从衣柜移除这件衣服？')+'<p class="modal-copy">已有收藏会保留搭配快照，但不会再标记这件衣物仍在衣柜中。</p><div class="button-row">'+button('先留着','cancel','secondary')+'<button class="primary" id="confirm-delete">确认移除</button></div>');$('#confirm-delete').onclick=()=>{if(persist(deleteItem(state,id))){closeModal();render();toast('已从衣柜移除')}}}}
async function start(item){active=item;variant=0;await generate()}
async function generate(){const n=++request;busy=true;view='result';app.innerHTML='<div class="loading-state"><div class="loading-orbit">'+icon('spark')+'</div><p class="eyebrow">STYLING IN PROGRESS</p><h1>给这件衣服，找个好搭档。</h1><p class="sub">正在准备模拟搭配… 不会发送照片到服务器。</p></div>';header();await new Promise(r=>setTimeout(r,650));if(n!==request)return;result=recommendation(active,scene,variant);busy=false;render();window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.matches('.brand')){e.preventDefault();go('home');return}if(b.hasAttribute('data-close')){closeModal();return}if(b.dataset.view){go(b.dataset.view);return}if(b.dataset.filter){filter=b.dataset.filter;render();return}if(b.dataset.item){detail(b.dataset.item);return}if(b.dataset.look){result=structuredClone(state.favorites.find(f=>f.id===b.dataset.look));active=result.top;scene=result.scene;variant=result.pants.id==='sample-blue'?1:0;go('result');return}if(b.dataset.removeFav){if(persist({...state,favorites:state.favorites.filter(f=>f.id!==b.dataset.removeFav)})){render();toast('已取消收藏')}return}
switch(b.dataset.action){case'home':go('home');break;case'upload':choosePhoto(true);break;case'add':case'found':choosePhoto(false);break;case'example':editDraft(structuredClone(samples[0]),true);break;case'choose':view='wardrobe';picker=true;filter='上衣';render();break;case'cancel':closeModal();break;case'next':if(!busy){variant=(variant+1)%2;generate()}break;case'favorite':if(!result)return;if(state.favorites.some(f=>f.id===result.id)){if(persist({...state,favorites:state.favorites.filter(f=>f.id!==result.id)})){render();toast('已取消收藏')}}else if(persist(saveFavorite(state,result))){render();toast('已收藏，在“收藏搭配”中随时查看')}break;case'reset':openModal(modalHead('重新开始这次体验？')+'<p class="modal-copy">将清除这个 Demo 中你上传的衣物和收藏，恢复最初两件示例衣物。此操作无法撤销。</p><div class="button-row">'+button('保留我的数据','cancel')+'<button class="primary" id="reset-confirm">重置演示数据</button></div>');$('#reset-confirm').onclick=()=>{if(persist(initialState())){closeModal();go('wardrobe');toast('已恢复示例衣柜')}};break}});
document.addEventListener('change',e=>{if(e.target.id==='scene'){scene=e.target.value;variant=0;generate()}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
render();
const context=document.modelContext;const lifecycle=new AbortController();if(context?.registerTool){for(const tool of [{name:'read_yida_demo',description:'Read local demo wardrobe counts and current view, without private photos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {view,wardrobe:state.wardrobe.map(({id,name,category})=>({id,name,category})),favorites:state.favorites.length}}},{name:'start_yida_demo_outfit',description:'Start a simulated outfit recommendation from an existing wardrobe top and display it. Does not save a favorite.',inputSchema:{type:'object',properties:{itemId:{type:'string'}},required:['itemId'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){const item=state.wardrobe.find(i=>i.id===input?.itemId&&i.category==='上衣');if(!item)throw Error('An existing top ID is required');await start(item);return {view,outfitId:result.id,mock:true}}}]){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
